### ISSUE TITLE
Define personas

### ISSUE THREAD

**Issue by turnerrainer** [buerokratt/Decision-Records#2]
AS AN Interested Party
I WANT TO have a full list of personas and their roles used throughout this project
SO THAT I would be on the same page with all other (active) participants of the project

### Acceptance Criteria

- [ ] Cover every persona with at least 1 sample user story
- [ ] Allow public discussion for every persona
- [ ] Add track-records to repository to keep history of changes
- [ ] Define final key decisions in Wiki

#### Scope

- [ ] #1 
- [ ] #3
- [ ] #4
- [ ] #5
- [ ] #6
- [ ] #7
- [ ] #8
- [ ] #9
- [ ] #10
- [ ] #11
